version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}
      - run:
          name: Run Lint
          command: ./gradlew lint --console plain
      - run:
          name: Run Unit Tests
          command: ./gradlew test --console plain
      - store_artifacts:
          path: build/lint-reports
          destination: reports
      - store_test_results:
          path: library/build/test-results
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}
